#!/bin/bash
echo"ALX"
echo"school" echo"The school is open"
"ALX" echo "ALX school"
echo"ALX" echo"The school is so cool!"
echo"ALX" echo"ALX school"
echo"school" echo"The school is open!"
echo"ALX" echoALX School
echo"ALX" echo"ALX school!"
echo"ALX" echo"ALX school"
